name: MLflow CI Training

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: credit_env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false

      - name: Install MLflow CLI
        run: |
          pip install mlflow

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --entry-point main
             - name: Upload model artifact
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: MLProject/output/model.pkl
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mlproject-model:latest MLProject

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mlproject-model:latest

