name: MLflow CI Training

on:
  push:
    branches:
      - main
    paths:
      - 'MLProject/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DATA_PATH: namadataset_preprocessing/creditapproval-data_preprocessing.csv
  MLFLOW_EXPERIMENT_NAME: mlflow-creditapproval
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/mlproject-model

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: MLProject/conda.yaml
          activate-environment: credit_env
          auto-activate-base: false

      - name: Install MLflow CLI
        run: pip install mlflow

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --entry-point main --params data_path=${{ env.DATA_PATH }}

      - name: Upload model artifact
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: MLProject/output/model.pkl

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_NAME }}:latest MLProject

      - name: Push Docker Image
        run: |
          docker push ${{ env.DOCKER_IMAGE_NAME }}:latest
