name: MLflow CI Training

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: credit_env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false

      - name: Install MLflow CLI
        run: |
          pip install mlflow

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --entry-point main
